# Generated by Django 3.2.23 on 2023-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
