# Generated by Django 3.2.23 on 2023-11-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='average_review_rating',
        ),
        migrations.AddField(
            model_name='package',
            name='difficulty_rating',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('challenging', 'Challenging')], default='easy', max_length=20),
        ),
    ]
