# Generated by Django 3.2.23 on 2023-11-10 10:42

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20231110_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='default_country',
            new_name='billing_country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='default_county',
            new_name='billing_county',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='billing_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_addressline_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_addressline_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_addressline_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_addressline_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_county',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
