# Generated by Django 3.2.23 on 2023-11-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20231110_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_addressline_1',
            new_name='addressline_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_addressline_2',
            new_name='addressline_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_county',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_phone_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_addressline_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_addressline_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_county',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone_number',
        ),
    ]
