# Generated by Django 3.2.23 on 2023-11-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_discountcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
