# Generated by Django 3.2.23 on 2023-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
