# Generated by Django 3.2.23 on 2023-11-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='difficulty_rating',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('challenging', 'Challenging')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], default='good', max_length=20),
        ),
    ]
