# Generated by Django 3.2.23 on 2023-11-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('percentage_discount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
