# Generated by Django 3.2.23 on 2023-11-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='default_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='default_county',
            new_name='county',
        ),
    ]
