# Generated by Django 3.2.23 on 2023-11-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_discountcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
